### ISSUE TITLE
[BUG] Manmelter counter overlaps the objective in a 4:3 aspect ratio

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#189] opened 2024-02-05 21:39 UTC
**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 640x480

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/2c3ae165-954a-4ecd-8fab-429ea9364f3c)

**Comment by CriticalFlaw** [comment] 2024-02-07 00:54
Closing as duplicate of #186

**Closed by CriticalFlaw** 2024-02-07 00:54 UTC
Labels: bug report, won't do/duplicate
