### ISSUE TITLE
[BUG] Respawn time is overlapped by the match HUD team dashboard in a 4:3 aspect ratio

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#194] opened 2024-02-07 10:20 UTC
It was tested at 12v12

**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 640x480
Minmode is used

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/d3b60485-b026-4991-b4cd-4a70001bc900)

**Comment by CriticalFlaw** [comment] 2024-02-07 12:52
Thats not a bug. Thats the outcome of playing on 4:3 resolution. It wont be fixed

**Comment by CriticalFlaw** [comment] 2024-02-10 18:06
This is because the match status player list is expanded. Because majority of players wouldn't be playing in 4:3 where this would be present, I won't be fixing this.

**Closed by CriticalFlaw** 2024-02-10 18:06 UTC
Labels: bug report
