### ISSUE TITLE
Spell display overlaps the Spy's current disguise

### ISSUE THREAD

**Issue by TheThunderGuyS** [CriticalFlaw/TF2HUD.Fixes#9] opened 2020-10-17 00:20 UTC
Currently the Halloween spell display overlaps with your Spy disguise as shown in the bottom left of this screenshot:
![image](https://user-images.githubusercontent.com/52540509/96323778-b3e8a980-0fec-11eb-8c35-7fe27e1ed94a.png)

This issue should probably be fixed, which is why I'm reporting it (also because I don't know how to fix it myself).
[#3418](https://github.com/ValveSoftware/Source-1-Games/issues/3418) on Valve repo.

**Comment by CriticalFlaw** [comment] 2020-10-17 01:56
Which resolution are you on?

**Comment by TheThunderGuyS** [comment] 2020-10-17 13:14
1920x1080 (sorry for the late reply, it was nighttime)

I also realized that there is no issue in the [ValveSoftware/Source-1-Games](https://github.com/ValveSoftware/Source-1-Games/) repo corresponding with this so I just created [#3418](https://github.com/ValveSoftware/Source-1-Games/issues/3418).

**Comment by CriticalFlaw** [comment] 2020-12-01 01:46
I haven't been able to replicate it on my end. Windows 10, same resolution.

![20201130204520_1](https://user-images.githubusercontent.com/6818236/100686778-04258c00-334d-11eb-8f83-64fba227eae7.jpg)

**Comment by TheThunderGuyS** [comment] 2020-12-03 22:23
On the latest commit, still happens for me.
![Image](https://user-images.githubusercontent.com/52540509/101095008-4805d480-358b-11eb-8844-d2dd045efb9b.png)

I don't know what else could possibly be causing this. This also occurs without minmode and with the default HUD.
I do notice you have a killstreak counter (being overlapped by the disguise) while I don't. This is probably the reason we get different results.

**Comment by CriticalFlaw** [comment] 2021-05-20 15:15
Could this be caused by the size of the player name? My name is shorter compared to yours so maybe the panel expands to give extra space. Could you test that out to verify?

**Comment by TheThunderGuyS** [comment] 2021-05-21 15:20
The size of the nickname and the display resolution don't seem to change anything. I have noticed however that for you the spell panel is further to the right than me, while everything else is in the same place. I have no idea what could cause this inconsistancy other than the killstreak panel.

**Comment by CriticalFlaw** [comment] 2021-05-24 17:38
Fixed in c3dd94369ba3f73276422f317d7ef2c9c66c57b6. Thanks!

**Closed by CriticalFlaw** 2021-05-24 17:38 UTC
Labels: bug
