### ISSUE TITLE
[BUG] Health above player's cut off

### ISSUE THREAD

**Issue by kittyra** [CriticalFlaw/TF2HUD.Fixes#76] opened 2022-07-31 15:16 UTC
**Issue**
When I hover over my teammate, it shows their health cut off. 

**Specifications**
Branch: community (latest version downloaded from source)
OS: Arch Linux 
Language: English 
Screen Resolution:1366x768 
Steps to reproduce: Hover over a teammate to see their health.

**Screenshots**
![Screenshot_20220731_170735](https://user-images.githubusercontent.com/110109711/182032803-81e9414b-12c9-4a1c-8359-9d748b3d2781.png)

**Comment by kittyra** [comment] 2022-07-31 16:49
Checked if it is the same on other resolutions, and it is. (I checked 1280x720 and 1024x768)

**Comment by kittyra** [comment] 2022-07-31 17:08
Weird... on the latest release (v2022.0630) I don't have this bug, maybe #75 broken something.
![1](https://user-images.githubusercontent.com/110109711/182037524-edd45c76-5984-4da8-a9b2-5cd0a4ed09a0.png)

It only occurs when a player has 300 hp and more.
![2](https://user-images.githubusercontent.com/110109711/182037538-6895296b-63e3-421c-9f0f-029b412ec387.png)

**Comment by CriticalFlaw** [comment] 2022-07-31 17:11
Yeah this was caused by the most recent change. Need to update the health icon class I think to make spectatorguihealth.

I'm out of town right now, returning tomorrow. Will look at it then unless someone else steps up

**Comment by CriticalFlaw** [comment] 2022-08-01 23:19
Fixed in 4cb33f98f9e4a26e90ae16c204ff1345c2a8f612
![20220801231836_1](https://user-images.githubusercontent.com/6818236/182261065-95457729-7833-4c01-a9a3-3a4c42d1bda9.jpg)

**Closed by CriticalFlaw** 2022-08-01 23:19 UTC
Labels: bug report
