### ISSUE TITLE
[BUG] Bazaar Bargain counter touches the objective in a 4:3 aspect ratio

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#192] opened 2024-02-05 22:07 UTC
**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 640x480

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/c2fa09dd-181d-4f69-a763-e50fa1919264)

**Comment by CriticalFlaw** [comment] 2024-02-07 00:55
Closing as duplicate of #186

**Closed by CriticalFlaw** 2024-02-07 00:55 UTC
Labels: bug report, won't do/duplicate
