### ISSUE TITLE
[BUG] Air Strike counter touches the objective in a 4:3 aspect ratio

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#188] opened 2024-02-05 21:35 UTC
**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 640x480

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/2b7c096c-26c6-477a-9322-11ec6351eb89)

**Comment by CriticalFlaw** [comment] 2024-02-07 00:54
Closing as duplicate of #186

**Closed by CriticalFlaw** 2024-02-07 00:54 UTC
Labels: bug report, won't do/duplicate
