### ISSUE TITLE
Syringe ammo counter representing "40" as "4..."

### ISSUE THREAD

**Issue by Sloofy** [CriticalFlaw/TF2HUD.Fixes#50] opened 2022-04-08 23:41 UTC
### Issue
When using any of the syringe guns, rather than a full clip showing 40, it will instead display "4...". 

### Specifications
Fedora Linux 35
Using the community branch up to the April 3rd, 2022 version
Playing at 1920x1080

### Screenshot
![Ammo](https://user-images.githubusercontent.com/18003771/162546857-8fa6d36e-82d2-40b5-b5b2-abd277cbb573.png)

**Comment by Sloofy** [comment] 2022-04-10 03:43
This affects the SMG too, as it turns out. While playing MVM last night, I also discovered that it only happens with the number 40 -- values below 39 and above 41. Haven't tested for triple digit values, but I can only assume this would be an issue though exclusive to custom gamemodes.

**Comment by CriticalFlaw** [comment] 2022-04-13 03:33
I'm not able to reproduce this issue on the latest `community` version in 16:9 resolution. Which version and resolution do you use?

**Comment by Sloofy** [comment] 2022-04-13 20:02
> I'm not able to reproduce this issue on the latest `community` version in 16:9 resolution. Which version and resolution do you use?

Latest community version with 1920x1080. I'm also playing on Linux, so maybe that could be where the issue is coming from? I wouldn't know for sure, though.

**Comment by CriticalFlaw** [comment] 2022-07-19 15:59
Compared to the original HUD files, the only difference is that the shadows are now pinned to the ammo label which itself shouldn't cause text truncation. I thought it may have been HudWeaponAmmo in hudlayout.res but it's the same as default. But if deleting the file does fix this then that'd be a good.

**Comment by CriticalFlaw** [comment] 2022-08-01 22:59
Fixed in fb30134dd216dbfbe24c4b4ced538a31ca31f0ae

**Closed by CriticalFlaw** 2022-08-01 22:59 UTC
Labels: bug report, linux
